// naukri import: scraper JSON → app/src/data/naukriSeed.js.
// ponytail: pure mapper (node --test) + tiny writer. Re-scrape → rerun with --in. No deps.
// usage: npm run jobs:import -- --in=/path/to/naukri_jobs.json
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));

// denylist first: core/support/mech titles no track serves. Checked before hints.
const DENY = ["maintenance", "service desk", "service engineer", "support", "field service", "mechanical", "hardware", "fea", "design engineer", "bioprocess", "purchase", "trainer", "recruiter", "candidate manager", "site sales"];
const HINTS = [
  ["data", ["data ", "analyst", "sql", "tableau", "power bi", "scientist", "machine learning", " ai ", "ml "]],
  ["marketing", ["marketing", "seo", "content", "social", "growth", "copywrit", "brand", " ads", "sales", "business development", "inside sales", "relationship manager", "customer service", "business executive"]],
  ["sde", ["develop", "engineer", "software", "frontend", "backend", "full-stack", "full stack", "web", "react", "node", "javascript", "python", "mobile", "devops", " qa", "qa ", "tester", "testing", "jmeter", "embedded", "android", "iot", "technical analyst", "data engineer"]],
  ["govt", ["ssc", "upsc", "bank po", "railway", "government"]],
];

const SKILL_DICT = ["react", "javascript", "node", "python", "sql", "java", "android", "embedded", "html", "css", "git", "api", "dsa", "qa", "testing", "jmeter", "seo", "content", "excel", "tableau", "iot", "c++"];

export function mapNaukri(j = {}, fallbackApply = "#") {
  const text = ` ${String(j.title || "")} `.toLowerCase();
  if (DENY.some((d) => text.includes(d))) return null;
  let role = null;
  for (const [r, hints] of HINTS) {
    if (hints.some((h) => text.includes(h))) { role = r; break; }
  }
  if (!role || !j.title) return null;
  const skills = [...new Set(SKILL_DICT.filter((s) => text.includes(s)).map((s) => (s === "c++" ? "dsa" : s)))].slice(0, 6);
  const exp = String(j.experience || "");
  return {
    id: `naukri-${j.id ?? text.slice(0, 12)}`,
    role,
    title: String(j.title).trim(),
    company: String(j.company || "Naukri employer").trim(),
    loc: String(j.location || "India").split(",")[0].replace(/\(.*/, "").replace(/hybrid\s*-\s*/i, "").trim() || "India",
    type: /intern|trainee|apprentice/i.test(j.title) ? "Internship" : "Full-time",
    skills,
    minScore: /^0/.test(exp) ? 40 : 50,
    apply: fallbackApply,
    src: "naukri",
    posted: j.posted || "",
    salary: j.salary || "",
  };
}

export function importNaukri(raw) {
  const seen = new Set();
  const jobs = [];
  let dropped = 0;
  for (const j of raw.jobs || []) {
    const m = mapNaukri(j, raw.url || "#");
    if (!m) { dropped++; continue; }
    const k = `${m.title.toLowerCase()}|${m.company.toLowerCase()}`;
    if (seen.has(k)) { dropped++; continue; }
    seen.add(k);
    jobs.push(m);
  }
  return { jobs, dropped, total: (raw.jobs || []).length };
}

const isMain = process.argv[1] === fileURLToPath(import.meta.url);
if (isMain) {
  // usage: npm run jobs:import -- --in=/path/to/naukri_jobs.json
  const arg = process.argv.find((a) => a.startsWith("--in="));
  if (!arg) {
    console.error("missing --in: npm run jobs:import -- --in=/path/to/naukri_jobs.json");
    process.exit(1);
  }
  const raw = JSON.parse(readFileSync(arg.slice(5), "utf8"));
  const { jobs, dropped, total } = importNaukri(raw);
  const out = `// auto-generated by npm run jobs:import from naukri_jobs.json — do not hand-edit.\n// source: ${raw.url || "naukri"} · scraped: ${raw.scraped_at || "?"} · ${jobs.length}/${total} mapped, ${dropped} dropped (off-track/dup).\n/* eslint-disable */\nexport const NAUKRI_JOBS = ${JSON.stringify(jobs, null, 2)};\n`;
  writeFileSync(join(HERE, "..", "src", "data", "naukriSeed.js"), out);
  console.log(`naukri: ${jobs.length}/${total} mapped, ${dropped} dropped → app/src/data/naukriSeed.js`);
}
